In [1]:
import numpy as np
import pandas as pd
import csv
import statistics

In [2]:
allSame = []
threeFourths = []
oneHalf = []
twoRatingsorLess = [] # the zero counts..
noRatings = []
allDifferent = []
aggloSAME = []
agglo75 = []
list2 = []

In [3]:
#df = pd.read_csv('/Users/amalalmansour/Desktop/New_Images/Malignancy/machine_ratings/machine_ratings.csv')
#rad_df = pd.read_csv('/Users/amalalmansour/Desktop/New_Images/Malignancy/machine_ratings/Radiologists_ratings.csv')
#f1 = pd.merge(df['noduleID'],rad_df)
df = pd.read_csv('/Users/amalalmansour/Desktop/New_Images/random_agreement/random_numbers30.csv')
display(df)

,m1,m2,m3,m4,noduleID,InstanceID,Agreement,Agglomeration,Binary Rating
0,1,2,4,2,1,4,NaN,NaN,NaN
1,5,1,4,2,5,118,NaN,NaN,NaN
2,3,3,5,2,3,134,NaN,NaN,NaN
3,4,2,4,5,4,143,NaN,NaN,NaN
4,3,5,1,4,6,175,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1327,4,5,5,2,2655,40771,NaN,NaN,NaN
1328,1,3,2,2,2657,40780,NaN,NaN,NaN
1329,4,5,5,2,2656,40794,NaN,NaN,NaN
1330,5,4,1,5,2658,40801,NaN,NaN,NaN
1331,4,3,3,5,2660,40860,NaN,NaN,NaN

In [4]:
length = 1332 #length of the input file..
counter = 0
for x in range(length):
    
    sp1 = df["m1"][x]
    sp2 = df["m2"][x]
    sp3 = df["m3"][x]
    sp4 = df["m4"][x]

    list2.append(sp1)
    list2.append(sp2)
    list2.append(sp3)
    list2.append(sp4)
    
    zeroCount = list2.count(0)
    #print(zeroCount)   
    
    # All agree... 
    if (sp1 == sp2 == sp3 == sp4):
        counter += 1
        allSame.append(x)
        aggloSAME.append(sp1) # one value from one of the radiologists

    # 75% agree...        
    elif ((sp1 == sp2 == sp3) or (sp1 == sp2 == sp4) or (sp1 == sp3 ==sp4) or (sp2 == sp3 == sp4)):
        threeFourths.append(x)
        #agglo75.append(round((sp1+sp2+sp3+sp4)/4)) # if 1 not spiculated if 0 spiculated
        agglo75.append(statistics.mode([sp1,sp2,sp3,sp4])) # if 1 not spiculated if 0 spiculated

    # 50% agree...
    elif (sp1 == sp2 or sp1 ==sp3 or sp1 == sp4 or sp2 == sp3 or sp2 == sp4 or sp3 == sp4):
        oneHalf.append(x)

    # none agree
    else:
        allDifferent.append(x)
list2.clear()

In [5]:
file_path1 = "/Users/amalalmansour/Desktop/AllAgree.csv"
print(counter)
allsameVal = []
allsameVal.append(df.columns)
for x in allSame:
    #print(allSame.index(x))
    aggloVal = aggloSAME[allSame.index(x)]
    
    df["Agglomeration"][x] = aggloVal
    if(aggloVal == 1):
        df["Binary Rating"][x] = 0 # not spiculated
    else:
        df["Binary Rating"][x] = 1 # spiculated
    arrRow = df.iloc[x]
    arrRow = arrRow.to_numpy()
    allsameVal.append(arrRow)
#np.savetxt(file_path1, allsameVal, fmt='%s', delimiter=',')
print(len(allsameVal))
#print(allsameVal)

16
17

<ipython-input-5-4cd29a035946>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Agglomeration"][x] = aggloVal
<ipython-input-5-4cd29a035946>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Binary Rating"][x] = 0 # not spiculated
<ipython-input-5-4cd29a035946>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Binary Rating"][x] = 1 # spiculated

In [6]:
file_path2 = "/Users/amalalmansour/Desktop/75agree.csv"
three4ths = []
three4ths.append(df.columns)
for x in threeFourths:
    aggloVal = agglo75[threeFourths.index(x)]
    df["Agglomeration"][x] = aggloVal
    if(aggloVal == 1):
        df["Binary Rating"][x] = 0 # not spiculated
    else:
        df["Binary Rating"][x] = 1 # spiculated
    arrRow = df.iloc[x]
    arrRow = arrRow.to_numpy()
    three4ths.append(arrRow)
#np.savetxt(file_path2, three4ths, fmt='%s', delimiter=',')
print(len(three4ths))

156

<ipython-input-6-3cfcb8a6423d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Agglomeration"][x] = aggloVal
<ipython-input-6-3cfcb8a6423d>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Binary Rating"][x] = 1 # spiculated
<ipython-input-6-3cfcb8a6423d>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Binary Rating"][x] = 0 # not spiculated

In [7]:
file_path3 = "/Users/amalalmansour/Desktop/50agree.csv"
halfAndHalf = []
halfAndHalf.append(df.columns)
for x in oneHalf:
    arrRow = df.iloc[x]
    arrRow = arrRow.to_numpy()
    halfAndHalf.append(arrRow)
#np.savetxt(file_path3, halfAndHalf, fmt='%s', delimiter=',')
print(len(halfAndHalf))

890

In [8]:
file_path4 = "/Users/amalalmansour/Desktop/NoneAgree.csv"
noAgree = []
noAgree.append(df.columns)
for x in allDifferent:
    arrRow = df.iloc[x]
    arrRow = arrRow.to_numpy()
    noAgree.append(arrRow)
#np.savetxt(file_path4, noAgree, fmt='%s', delimiter=',')
print(len(noAgree))

273