In [1]:
import pandas as pd
import numpy as np
from statsmodels.stats import inter_rater as irr
import krippendorff as kd

In [2]:
arr = [[1, 0, 5, 4, 2],
       [1, 3, 0, 4, 1],
       [1, 3, 5, 2, 0],
       [0, 3, 4, 4, 5]]

# Remove 0 values from the 2D list
arr_without_zeros = [[value for value in row if value != 0] for row in arr]
arr_without_zeros

[[1, 5, 4, 2], [1, 3, 4, 1], [1, 3, 5, 2], [3, 4, 4, 5]]

In [192]:
data = {
    'rater1': [1, 5, 5, 4, 2,3,4],
    'rater2': [1, 4, 5, 4, 2,3,4],
    'rater3': [1, 1, 5, 4, 2,3,4],
    'rater4': [1, 1, 5, 4, 2,3,4]
}

df = pd.DataFrame(data)

# Create new columns for each rating (1-5) and initialize them with zeros
for rating in range(1, 6):
    df[f'column{rating}'] = 0

# Iterate over each row and count the ratings for that row
for i in range(len(df)):
    for rating in range(1, 6):
        count = (df.iloc[i, :-5] == rating).sum()
        df.at[i, f'column{rating}'] = count
        

print(df)

   rater1  rater2  rater3  rater4  column1  column2  column3  column4  column5
0       1       1       1       1        4        0        0        0        0
1       5       4       1       1        2        0        0        1        1
2       5       5       5       5        0        0        0        0        4
3       4       4       4       4        0        0        0        4        0
4       2       2       2       2        0        4        0        0        0
5       3       3       3       3        0        0        4        0        0
6       4       4       4       4        0        0        0        4        0

In [72]:
data = {
    'rater1': [1, 5, 3, 4, 2],
    'rater2': [1, 5, 3, 4, 2],
    'rater3': [1, 3, 3, 4, 2],
    'rater4': [1, 3, 3, 4, 2]
}

df = pd.DataFrame(data)

# Create new columns for each rating (1-5) and initialize them with zeros
for rating in range(1, 6):
    df[f'column{rating}'] = 0

# Create a 'total' column to store the total count for each row
df['total'] = 0

# Iterate over each row and count the ratings for that row
for i in range(len(df)):
    for rating in range(1, 6):
        count = (df.iloc[i, :-6] == rating).sum()
        df.at[i, f'column{rating}'] = count
    total_count = df.iloc[i, -6:-1].sum()  # Sum the counts for columns 'column1' to 'column5'
    df.at[i, 'total'] = total_count

print(df)

   rater1  rater2  rater3  rater4  column1  column2  column3  column4  \
0       1       1       1       1        4        0        0        0
1       5       5       3       3        0        0        2        0
2       3       3       3       3        0        0        4        0
3       4       4       4       4        0        0        0        4
4       2       2       2       2        0        4        0        0

   column5  total
0        0      4
1        2      4
2        0      4
3        0      4
4        0      4

In [73]:
df.iloc[1, -6:]

column1    0
column2    0
column3    2
column4    0
column5    2
total      4
Name: 1, dtype: int64

In [74]:
#df_fleiss = df[['column1','column2', 'column3', 'column4', 'column5']]

In [75]:
df_fleiss = df[['rater1','rater2', 'rater3', 'rater4']]

In [76]:
df_fleiss

   rater1  rater2  rater3  rater4
0       1       1       1       1
1       5       5       3       3
2       3       3       3       3
3       4       4       4       4
4       2       2       2       2

In [77]:
pre_fleiss = df_fleiss.values
dats, cats = irr.aggregate_raters(pre_fleiss)

In [78]:
dats

array([[4, 0, 0, 0, 0],
       [0, 0, 2, 0, 2],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 4, 0, 0, 0]])

In [79]:
cats

array([1, 2, 3, 4, 5])

In [80]:
irr.fleiss_kappa(dats, method= 'fleiss')

0.8290598290598288

In [81]:
kd.alpha(pre_fleiss.transpose())

0.8376068376068376

In [52]:
mal = pd.read_csv('/Users/amalalmansour/Desktop/New_Images/Malignancy/Agreement_Binary_Rating.csv')
len(mal)

1332

In [15]:
display(mal)

,InstanceID,RadiologistID,noduleID,imageZposition,Area,ConvexArea,Malignancy_1,Malignancy_2,Malignancy_3,Malignancy_4,Malignancy,Binary Rating,Binary_Rating_name,Agreement,Agreement_name,Two_Agreement,Two_Agreement_name
0,4,1,1,-117.500000,1094,1286,5,5,5,4,5,1,Malignant,2,High Radiologist Agreement,1,Full_High
1,118,3,5,-169.000000,246,251,4,5,3,2,4,3,Unknown,0,No Radiologist Agreement,0,Low_No
2,134,4,3,-186.500000,931,1062,5,5,3,4,5,3,Unknown,1,Low Radiologist Agreement,0,Low_No
3,143,4,4,-171.500000,161,167,4,4,3,2,4,3,Unknown,1,Low Radiologist Agreement,0,Low_No
4,175,4,6,-230.000000,71,73,2,1,1,1,1,0,Benign,2,High Radiologist Agreement,1,Full_High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1327,40771,4,2655,-199.500000,73,75,0,2,3,2,2,3,Unknown,1,Low Radiologist Agreement,0,Low_No
1328,40780,1,2657,-188.000000,638,759,3,5,5,5,5,1,Malignant,2,High Radiologist Agreement,1,Full_High
1329,40794,2,2656,-153.000000,437,464,2,5,5,5,5,1,Malignant,2,High Radiologist Agreement,1,Full_High
1330,40801,2,2658,-228.000000,657,674,4,3,4,3,4,3,Unknown,1,Low Radiologist Agreement,0,Low_No
1331,40860,3,2660,-167.455002,139,142,2,2,2,2,2,0,Benign,3,Full Radiologists Agreement,1,Full_High

In [16]:
df_rating = mal[['Malignancy_1', 'Malignancy_2', 'Malignancy_3', 'Malignancy_4']]
df_rating

      Malignancy_1  Malignancy_2  Malignancy_3  Malignancy_4
0                5             5             5             4
1                4             5             3             2
2                5             5             3             4
3                4             4             3             2
4                2             1             1             1
...            ...           ...           ...           ...
1327             0             2             3             2
1328             3             5             5             5
1329             2             5             5             5
1330             4             3             4             3
1331             2             2             2             2

[1332 rows x 4 columns]

In [17]:
# Create new columns for each rating (1-5) and initialize them with zeros
for rating in range(1, 6):
    df_rating[f'column{rating}'] = 0
    
# Create a 'total' column to store the total count for each row
mal['total'] = 0

<ipython-input-17-255048f57372>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rating[f'column{rating}'] = 0

In [18]:
# Iterate over each row and count the ratings for that row
for i in range(len(df_rating)):
    for rating in range(1, 6):
        count = (df_rating.iloc[i, :-5] == rating).sum()
        df_rating.at[i, f'column{rating}'] = count
    total_count = df_rating.iloc[i, -5:].sum()  # Sum the counts for columns 'column1' to 'column5'
    mal.at[i, 'total'] = total_count

print(mal['total'])

0       4
1       4
2       4
3       4
4       4
       ..
1327    3
1328    4
1329    4
1330    4
1331    4
Name: total, Length: 1332, dtype: int64

In [19]:
print(mal)

      InstanceID  RadiologistID  noduleID  imageZposition  Area  ConvexArea  \
0              4              1         1     -117.500000  1094        1286
1            118              3         5     -169.000000   246         251
2            134              4         3     -186.500000   931        1062
3            143              4         4     -171.500000   161         167
4            175              4         6     -230.000000    71          73
...          ...            ...       ...             ...   ...         ...
1327       40771              4      2655     -199.500000    73          75
1328       40780              1      2657     -188.000000   638         759
1329       40794              2      2656     -153.000000   437         464
1330       40801              2      2658     -228.000000   657         674
1331       40860              3      2660     -167.455002   139         142

      Malignancy_1  Malignancy_2  Malignancy_3  Malignancy_4  Malignancy  \
0                5             5             5             4           5
1                4             5             3             2           4
2                5             5             3             4           5
3                4             4             3             2           4
4                2             1             1             1           1
...            ...           ...           ...           ...         ...
1327             0             2             3             2           2
1328             3             5             5             5           5
1329             2             5             5             5           5
1330             4             3             4             3           4
1331             2             2             2             2           2

      Binary Rating Binary_Rating_name  Agreement  \
0                 1          Malignant          2
1                 3            Unknown          0
2                 3            Unknown          1
3                 3            Unknown          1
4                 0             Benign          2
...             ...                ...        ...
1327              3            Unknown          1
1328              1          Malignant          2
1329              1          Malignant          2
1330              3            Unknown          1
1331              0             Benign          3

                   Agreement_name  Two_Agreement Two_Agreement_name  total
0      High Radiologist Agreement              1          Full_High      4
1        No Radiologist Agreement              0             Low_No      4
2       Low Radiologist Agreement              0             Low_No      4
3       Low Radiologist Agreement              0             Low_No      4
4      High Radiologist Agreement              1          Full_High      4
...                           ...            ...                ...    ...
1327    Low Radiologist Agreement              0             Low_No      3
1328   High Radiologist Agreement              1          Full_High      4
1329   High Radiologist Agreement              1          Full_High      4
1330    Low Radiologist Agreement              0             Low_No      4
1331  Full Radiologists Agreement              1          Full_High      4

[1332 rows x 18 columns]

In [20]:
print(mal['total'].value_counts())

4    826
3    506
Name: total, dtype: int64

In [21]:
full_agreement = mal[mal['Agreement'] == 3]
high_agreement = mal[mal['Agreement'] == 2]
low_agreement = mal[mal['Agreement'] == 1]
no_agreement =  mal[mal['Agreement'] == 0]

In [22]:
full_agreement

,InstanceID,RadiologistID,noduleID,imageZposition,Area,ConvexArea,Malignancy_1,Malignancy_2,Malignancy_3,Malignancy_4,Malignancy,Binary Rating,Binary_Rating_name,Agreement,Agreement_name,Two_Agreement,Two_Agreement_name,total
56,1352,2,104,-126.250000,95,101,1,1,1,1,1,0,Benign,3,Full Radiologists Agreement,1,Full_High,4
137,3528,4,244,-35.000000,165,172,3,3,3,3,3,2,Undetermain,3,Full Radiologists Agreement,1,Full_High,4
195,5115,3,348,-214.500000,370,385,1,1,1,1,1,0,Benign,3,Full Radiologists Agreement,1,Full_High,4
196,5123,3,349,-180.500000,119,123,1,1,1,1,1,0,Benign,3,Full Radiologists Agreement,1,Full_High,4
248,6517,2,440,-303.000000,67,68,1,1,1,1,1,0,Benign,3,Full Radiologists Agreement,1,Full_High,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1268,38722,3,2521,1382.000000,82,85,1,1,1,1,1,0,Benign,3,Full Radiologists Agreement,1,Full_High,4
1296,39806,1,2594,-137.600000,127,128,1,1,1,1,1,0,Benign,3,Full Radiologists Agreement,1,Full_High,4
1303,39936,3,2609,-52.680000,53,54,1,1,1,1,1,0,Benign,3,Full Radiologists Agreement,1,Full_High,4
1304,39941,4,2610,-81.430000,69,72,3,3,3,3,3,2,Undetermain,3,Full Radiologists Agreement,1,Full_High,4
1331,40860,3,2660,-167.455002,139,142,2,2,2,2,2,0,Benign,3,Full Radiologists Agreement,1,Full_High,4

In [23]:
high_agreement

,InstanceID,RadiologistID,noduleID,imageZposition,Area,ConvexArea,Malignancy_1,Malignancy_2,Malignancy_3,Malignancy_4,Malignancy,Binary Rating,Binary_Rating_name,Agreement,Agreement_name,Two_Agreement,Two_Agreement_name,total
0,4,1,1,-117.500000,1094,1286,5,5,5,4,5,1,Malignant,2,High Radiologist Agreement,1,Full_High,4
4,175,4,6,-230.000000,71,73,2,1,1,1,1,0,Benign,2,High Radiologist Agreement,1,Full_High,4
5,179,1,7,-145.044998,67,67,3,3,3,2,3,2,Undetermain,2,High Radiologist Agreement,1,Full_High,4
6,195,4,8,-140.044998,120,127,3,3,3,2,3,2,Undetermain,2,High Radiologist Agreement,1,Full_High,4
10,297,2,17,-125.720001,72,80,3,3,3,2,3,2,Undetermain,2,High Radiologist Agreement,1,Full_High,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1299,39889,3,2602,-138.500000,76,91,3,3,3,0,3,2,Undetermain,2,High Radiologist Agreement,1,Full_High,3
1320,40605,4,2634,-130.779999,56,56,2,2,2,3,2,0,Benign,2,High Radiologist Agreement,1,Full_High,4
1324,40684,1,2647,-207.100000,1372,1816,5,5,5,0,5,1,Malignant,2,High Radiologist Agreement,1,Full_High,3
1328,40780,1,2657,-188.000000,638,759,3,5,5,5,5,1,Malignant,2,High Radiologist Agreement,1,Full_High,4
1329,40794,2,2656,-153.000000,437,464,2,5,5,5,5,1,Malignant,2,High Radiologist Agreement,1,Full_High,4

In [24]:
low_agreement

,InstanceID,RadiologistID,noduleID,imageZposition,Area,ConvexArea,Malignancy_1,Malignancy_2,Malignancy_3,Malignancy_4,Malignancy,Binary Rating,Binary_Rating_name,Agreement,Agreement_name,Two_Agreement,Two_Agreement_name,total
2,134,4,3,-186.500000,931,1062,5,5,3,4,5,3,Unknown,1,Low Radiologist Agreement,0,Low_No,4
3,143,4,4,-171.500000,161,167,4,4,3,2,4,3,Unknown,1,Low Radiologist Agreement,0,Low_No,4
7,200,1,2661,-121.500000,150,154,3,4,3,2,3,3,Unknown,1,Low Radiologist Agreement,0,Low_No,4
8,270,3,15,-87.000000,915,1017,0,5,5,4,5,3,Unknown,1,Low Radiologist Agreement,0,Low_No,3
9,291,1,16,-168.220001,75,77,3,3,0,2,3,3,Unknown,1,Low Radiologist Agreement,0,Low_No,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1323,40658,4,2640,-153.000000,174,188,2,3,3,2,3,3,Unknown,1,Low Radiologist Agreement,0,Low_No,4
1325,40720,3,2646,-228.700000,83,87,4,2,1,2,2,3,Unknown,1,Low Radiologist Agreement,0,Low_No,4
1326,40751,4,2649,1466.500000,74,77,3,0,3,2,3,3,Unknown,1,Low Radiologist Agreement,0,Low_No,3
1327,40771,4,2655,-199.500000,73,75,0,2,3,2,2,3,Unknown,1,Low Radiologist Agreement,0,Low_No,3
1330,40801,2,2658,-228.000000,657,674,4,3,4,3,4,3,Unknown,1,Low Radiologist Agreement,0,Low_No,4

In [25]:
no_agreement

,InstanceID,RadiologistID,noduleID,imageZposition,Area,ConvexArea,Malignancy_1,Malignancy_2,Malignancy_3,Malignancy_4,Malignancy,Binary Rating,Binary_Rating_name,Agreement,Agreement_name,Two_Agreement,Two_Agreement_name,total
1,118,3,5,-169.000000,246,251,4,5,3,2,4,3,Unknown,0,No Radiologist Agreement,0,Low_No,4
15,425,1,34,-195.250000,219,222,4,3,5,2,4,3,Unknown,0,No Radiologist Agreement,0,Low_No,4
26,599,2,47,-135.250000,449,482,4,3,5,2,4,3,Unknown,0,No Radiologist Agreement,0,Low_No,4
32,742,4,54,-199.750000,518,535,0,4,5,3,4,3,Unknown,0,No Radiologist Agreement,0,Low_No,3
42,1042,3,72,-135.750000,227,236,0,3,1,2,2,3,Unknown,0,No Radiologist Agreement,0,Low_No,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1290,39539,3,2579,-101.705002,104,106,3,2,1,0,2,3,Unknown,0,No Radiologist Agreement,0,Low_No,3
1291,39579,2,2582,720.400024,121,132,2,4,3,0,3,3,Unknown,0,No Radiologist Agreement,0,Low_No,3
1295,39779,4,2585,-95.059998,438,450,3,4,0,2,3,3,Unknown,0,No Radiologist Agreement,0,Low_No,3
1298,39871,1,2603,-129.500000,78,80,3,2,4,0,3,3,Unknown,0,No Radiologist Agreement,0,Low_No,3
1313,40328,1,2625,-204.600000,108,109,2,1,3,0,2,3,Unknown,0,No Radiologist Agreement,0,Low_No,3

In [26]:
full = full_agreement[['Malignancy_1', 'Malignancy_2', 'Malignancy_3', 'Malignancy_4']]
fdats, fcats = irr.aggregate_raters(full.values)
print(irr.fleiss_kappa(fdats, method= 'fleiss'))
print(kd.alpha(full.values.transpose()))

1.0
1.0

In [27]:
high = high_agreement[['Malignancy_1', 'Malignancy_2', 'Malignancy_3', 'Malignancy_4']]
#hdats, hcats = irr.aggregate_raters(high.values)
#print(irr.fleiss_kappa(hdats, method= 'fleiss'))
arr_without_zeros_high = [[value for value in row if value != 0] for row in high.values]
# Transpose the 2D list
arr_transposed_high = [list(x) for x in zip(*arr_without_zeros_high)]
print(kd.alpha(arr_transposed_high))

0.7627034780326305

In [28]:
low = low_agreement[['Malignancy_1', 'Malignancy_2', 'Malignancy_3', 'Malignancy_4']]
#ldats, lcats = irr.aggregate_raters(low.values)
#print(irr.fleiss_kappa(ldats, method= 'fleiss'))
arr_without_zeros_low = [[value for value in row if value != 0] for row in low.values]
# Transpose the 2D list
arr_transposed_low = [list(x) for x in zip(*arr_without_zeros_low)]
print(kd.alpha(arr_transposed_low))

0.33206743267654015

In [29]:
no = no_agreement[['Malignancy_1', 'Malignancy_2', 'Malignancy_3', 'Malignancy_4']]
#ndats, ncats = irr.aggregate_raters(no.values)
#print(irr.fleiss_kappa(ndats, method= 'fleiss'))
arr_without_zeros_no = [[value for value in row if value != 0] for row in no.values]
# Transpose the 2D list
arr_transposed_no = [list(x) for x in zip(*arr_without_zeros_no)]
print(kd.alpha(arr_transposed_no))

-0.052890615952751574

# Fleiss Kappa ...

In [30]:
high_4_ratings = high_agreement[high_agreement['total'] == 4]
high_3_ratings = high_agreement[high_agreement['total'] == 3]
print('high_4_ratings len:',len(high_4_ratings))
print('high_3_ratings len:',len(high_3_ratings))

high_4_ratings = high_4_ratings[['Malignancy_1', 'Malignancy_2', 'Malignancy_3', 'Malignancy_4']]
hdats4, hcats4 = irr.aggregate_raters(high_4_ratings.values)
print('high_4_ratings:',irr.fleiss_kappa(hdats4, method= 'fleiss'))

high_4_ratings len: 241
high_3_ratings len: 91
high_4_ratings: 0.3119363599477564

In [31]:
high_3_ratings = high_3_ratings[['Malignancy_1', 'Malignancy_2', 'Malignancy_3', 'Malignancy_4']]
arr_without_zeros = [[value for value in row if value != 0] for row in high_3_ratings.values]

In [32]:
hdats3, hcats3 = irr.aggregate_raters(arr_without_zeros)
print('high_3_ratings:',irr.fleiss_kappa(hdats3, method= 'fleiss'))

high_3_ratings: 1.0

In [33]:
low_4_ratings = low_agreement[low_agreement['total'] == 4]
low_3_ratings = low_agreement[low_agreement['total'] == 3]
print('low_4_ratings len:',len(low_4_ratings))
print('low_3_ratings len:',len(low_3_ratings))

low_4_ratings = low_4_ratings[['Malignancy_1', 'Malignancy_2', 'Malignancy_3', 'Malignancy_4']]
ldats4, lcats4 = irr.aggregate_raters(low_4_ratings.values)
print('low_4_ratings:',irr.fleiss_kappa(ldats4, method= 'fleiss'))

low_4_ratings len: 432
low_3_ratings len: 315
low_4_ratings: -0.04886159960400363

In [155]:
np.unique(low_4_ratings)

array([1, 2, 3, 4, 5])

In [34]:
low_3_ratings = low_3_ratings[['Malignancy_1', 'Malignancy_2', 'Malignancy_3', 'Malignancy_4']]
arr_without_zeros_low3 = [[value for value in row if value != 0] for row in low_3_ratings.values]
ldats3, lcats3 = irr.aggregate_raters(arr_without_zeros_low3)
print('low_3_ratings:',irr.fleiss_kappa(ldats3, method= 'fleiss'))

low_3_ratings: 0.04782087165133946

In [154]:
np.unique(arr_without_zeros_low3)

array([1, 2, 3, 4, 5])

In [35]:
no_4_ratings = no_agreement[no_agreement['total'] == 4]
no_3_ratings = no_agreement[no_agreement['total'] == 3]
print('no_4_ratings len:',len(no_4_ratings))
print('no_3_ratings len:',len(no_3_ratings))

no_4_ratings = no_4_ratings[['Malignancy_1', 'Malignancy_2', 'Malignancy_3', 'Malignancy_4']]
ndats4, ncats4 = irr.aggregate_raters(no_4_ratings.values)
print('no_4_ratings:',irr.fleiss_kappa(ndats4, method= 'fleiss'))

no_4_ratings len: 54
no_3_ratings len: 100
no_4_ratings: -0.2701039908531605

In [149]:
np.unique(no_4_ratings)

array([1, 2, 3, 4, 5])

In [36]:
no_3_ratings = no_3_ratings[['Malignancy_1', 'Malignancy_2', 'Malignancy_3', 'Malignancy_4']]
arr_without_zeros_no3 = [[value for value in row if value != 0] for row in no_3_ratings.values]
ndats3, ncats3 = irr.aggregate_raters(arr_without_zeros_no3)
print('no_3_ratings:',irr.fleiss_kappa(ndats3, method= 'fleiss'))

no_3_ratings: -0.3040832294896688

In [148]:
np.unique(arr_without_zeros_no3)

array([1, 2, 3, 4, 5])

In [37]:
all_data_4_ratings = mal[mal['total'] == 4]
all_data_3_ratings = mal[mal['total'] == 3]
print('all_data_4_ratings len:',len(all_data_4_ratings))
print('all_data_3_ratings len:',len(all_data_3_ratings))

all_data_4_ratings = all_data_4_ratings[['Malignancy_1', 'Malignancy_2', 'Malignancy_3', 'Malignancy_4']]
dats4, cats4 = irr.aggregate_raters(all_data_4_ratings.values)
print('all_data_4_ratings:',irr.fleiss_kappa(dats4, method= 'fleiss'))

all_data_4_ratings len: 826
all_data_3_ratings len: 506
all_data_4_ratings: 0.19244363198968528

In [150]:
np.unique(all_data_4_ratings)

array([1, 2, 3, 4, 5])

In [38]:
all_data_3_ratings = all_data_3_ratings[['Malignancy_1', 'Malignancy_2', 'Malignancy_3', 'Malignancy_4']]
arr_without_zeros_all_data_3 = [[value for value in row if value != 0] for row in all_data_3_ratings.values]
dats3, cats3 = irr.aggregate_raters(arr_without_zeros_all_data_3)
print('all_data_3_ratings:',irr.fleiss_kappa(dats3, method= 'fleiss'))

all_data_3_ratings: 0.16145449102436615

In [152]:
np.unique(arr_without_zeros_all_data_3)

array([1, 2, 3, 4, 5])

In [39]:
mal_all = mal[['Malignancy_1', 'Malignancy_2', 'Malignancy_3', 'Malignancy_4']]
arr_without_zeros_mal_all = [[value for value in row if value != 0] for row in mal_all.values]
# Transpose the 2D list
arr_transposed = [list(x) for x in zip(*arr_without_zeros_mal_all)]
print(kd.alpha(arr_transposed))

0.5131717017110735

In [153]:
np.unique(arr_transposed)

array([1, 2, 3, 4, 5])

In [40]:
#high_3_ratings

In [41]:
#dats3, cats3 = irr.aggregate_raters(high_3_ratings.values)
#print('all_data_3_ratings:',irr.fleiss_kappa(dats3, method= 'fleiss'))